// src/app/(main)/profile/page.tsx
import React from "react";
import { redirect } from "next/navigation";
import Image from "next/image";
import { Trophy, Flame, Bookmark, MessageSquare, Calendar } from "lucide-react";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { levelProgress } from "@/lib/leveling";

export const metadata = {
  title: "Hồ Sơ Cá Nhân & Cấp Bậc — TruyenKomi",
  description: "Xem hồ sơ cá nhân, tiến trình EXP, cấp bậc độc giả và chuỗi ngày đọc truyện liên tục.",
};

export default async function ProfilePage() {
  const session = await auth();
  if (!session?.user?.id) {
    redirect("/login?next=/profile");
  }

  const [user, followsCount, commentsCount] = await Promise.all([
    prisma.user.findUnique({
      where: { id: session.user.id },
      select: {
        id: true,
        username: true,
        email: true,
        avatar: true,
        role: true,
        exp: true,
        level: true,
        dailyStreak: true,
        createdAt: true,
        lastActiveAt: true,
      },
    }),
    prisma.follow.count({ where: { userId: session.user.id } }),
    prisma.comment.count({ where: { userId: session.user.id } }),
  ]);

  if (!user) {
    redirect("/login");
  }

  const progress = levelProgress(user.exp);

  return (
    <div className="mx-auto max-w-4xl space-y-8">
      {/* Profile Header Card */}
      <div className="relative overflow-hidden rounded-3xl border border-zinc-800 bg-zinc-900/80 p-6 sm:p-8 shadow-2xl">
        <div className="flex flex-col sm:flex-row items-center gap-6">
          {/* Avatar */}
          <div className="relative h-24 w-24 shrink-0 overflow-hidden rounded-full bg-gradient-to-tr from-orange-500 to-amber-500 p-1 ring-4 ring-orange-500/20 shadow-xl">
            <div className="relative h-full w-full rounded-full overflow-hidden bg-zinc-950 flex items-center justify-center font-bold text-3xl text-orange-400">
              {user.avatar ? (
                <Image src={user.avatar} alt={user.username} fill sizes="96px" className="object-cover" />
              ) : (
                user.username[0]?.toUpperCase() || "U"
              )}
            </div>
          </div>

          {/* User Info */}
          <div className="flex flex-1 flex-col items-center sm:items-start text-center sm:text-left space-y-2">
            <div className="flex flex-wrap items-center gap-2.5">
              <h1 className="text-2xl font-black text-zinc-100">{user.username}</h1>
              <span className="rounded-md bg-orange-500/20 px-2.5 py-0.5 text-xs font-bold text-orange-400 border border-orange-500/30">
                {user.role}
              </span>
            </div>
            <p className="text-xs text-zinc-400">{user.email}</p>
            <div className="flex items-center gap-2 text-xs text-zinc-500 pt-1">
              <Calendar className="h-3.5 w-3.5" />
              <span>Gia nhập: {new Date(user.createdAt).toLocaleDateString("vi-VN")}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Gamification Level & EXP Progress */}
      <div className="rounded-3xl border border-zinc-800 bg-zinc-900/60 p-6 sm:p-8 shadow-xl space-y-6">
        <div className="flex items-center justify-between border-b border-zinc-800 pb-4">
          <div className="flex items-center gap-2">
            <Trophy className="h-5 w-5 text-orange-500" />
            <h2 className="text-base font-bold text-zinc-100">Cấp Bậc & Điểm Kinh Nghiệm (EXP)</h2>
          </div>
          <span className="rounded-xl bg-gradient-to-r from-orange-500 to-amber-500 px-3.5 py-1 text-xs font-black text-white shadow-md shadow-orange-500/20">
            CẤP {progress.level}
          </span>
        </div>

        {/* EXP Bar */}
        <div className="space-y-2">
          <div className="flex items-center justify-between text-xs font-semibold">
            <span className="text-zinc-400">Tiến trình lên Cấp {progress.level + 1}</span>
            <span className="text-orange-400 font-bold">
              {progress.exp} / {progress.nextFloor} EXP ({progress.progressPct}%)
            </span>
          </div>

          <div className="h-3 w-full overflow-hidden rounded-full bg-zinc-800">
            <div
              className="h-full rounded-full bg-gradient-to-r from-orange-500 to-amber-400 transition-all duration-500"
              style={{ width: `${progress.progressPct}%` }}
            />
          </div>
          <p className="text-[11px] text-zinc-500 text-right">
            Còn thiếu {progress.nextFloor - progress.exp} EXP để thăng cấp tiếp theo
          </p>
        </div>

        {/* How to get EXP Guide */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2 text-center text-xs">
          <div className="rounded-2xl border border-zinc-800/80 bg-zinc-800/40 p-3">
            <p className="font-bold text-orange-400">+20 EXP</p>
            <p className="mt-1 text-[11px] text-zinc-400">Đăng nhập mỗi ngày</p>
          </div>
          <div className="rounded-2xl border border-zinc-800/80 bg-zinc-800/40 p-3">
            <p className="font-bold text-amber-400">+5 EXP</p>
            <p className="mt-1 text-[11px] text-zinc-400">Đọc 1 chương truyện</p>
          </div>
          <div className="rounded-2xl border border-zinc-800/80 bg-zinc-800/40 p-3">
            <p className="font-bold text-emerald-400">+10 EXP</p>
            <p className="mt-1 text-[11px] text-zinc-400">Gửi 1 bình luận</p>
          </div>
          <div className="rounded-2xl border border-zinc-800/80 bg-zinc-800/40 p-3">
            <p className="font-bold text-sky-400">+10 EXP</p>
            <p className="mt-1 text-[11px] text-zinc-400">Đánh giá sao truyện</p>
          </div>
        </div>
      </div>

      {/* Activity Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="flex items-center gap-4 rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5 shadow-xl">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-500/15 text-amber-500">
            <Flame className="h-6 w-6" />
          </div>
          <div>
            <p className="text-2xl font-black text-zinc-100">{user.dailyStreak || 0}</p>
            <p className="text-xs text-zinc-400">Chuỗi ngày đọc (Streak)</p>
          </div>
        </div>

        <div className="flex items-center gap-4 rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5 shadow-xl">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-500/15 text-orange-400">
            <Bookmark className="h-6 w-6" />
          </div>
          <div>
            <p className="text-2xl font-black text-zinc-100">{followsCount}</p>
            <p className="text-xs text-zinc-400">Truyện đang theo dõi</p>
          </div>
        </div>

        <div className="flex items-center gap-4 rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5 shadow-xl">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-sky-500/15 text-sky-400">
            <MessageSquare className="h-6 w-6" />
          </div>
          <div>
            <p className="text-2xl font-black text-zinc-100">{commentsCount}</p>
            <p className="text-xs text-zinc-400">Bình luận đã gửi</p>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/pages/profile/profile.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthService, ToastService } from '../../core/services/core-services';
import { UserService } from '../../core/services/app-services';
import { User } from '../../core/models';
import { IconComponent } from '../../shared/components/icon.component';
import { SafeImageComponent, ModalComponent } from '../../shared/components/ui-components';

@Component({
  selector: 'app-profile-page',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, IconComponent, ModalComponent],
  template: `
    <div class="container mx-auto px-4 py-8 max-w-4xl">
      <!-- Breadcrumb -->
      <div class="flex items-center gap-2 text-sm text-[var(--text-muted)] mb-6">
        <a routerLink="/" class="hover:text-[var(--accent)] transition-colors">Trang chủ</a>
        <span>/</span>
        <span class="text-[var(--text-primary)]">Hồ sơ cá nhân</span>
      </div>

      @if (auth.currentUser(); as user) {
        <div class="space-y-6">
          <!-- Profile Card -->
          <div class="bg-[var(--bg-card)] border border-[var(--border)] rounded-3xl p-6 sm:p-8 relative overflow-hidden shadow-lg">
            <!-- Ambient glow -->
            <div class="absolute -right-20 -top-20 w-72 h-72 bg-[var(--accent)]/15 rounded-full blur-3xl pointer-events-none"></div>

            <div class="relative z-10 flex flex-col sm:flex-row items-center sm:items-start gap-6">
              <!-- Avatar with edit trigger -->
              <div class="relative group cursor-pointer" (click)="openAvatarModal()">
                <div class="w-28 h-28 sm:w-32 sm:h-32 rounded-3xl overflow-hidden border-2 border-[var(--accent)]/40 p-1 bg-[var(--bg-secondary)] shadow-md">
                  @if (user.avatar) {
                    <img [src]="user.avatar" [alt]="user.username" class="w-full h-full object-cover rounded-2xl" />
                  } @else {
                    <div class="w-full h-full rounded-2xl bg-[var(--accent)]/20 text-[var(--accent)] flex items-center justify-center font-black text-3xl">
                      {{ user.username.charAt(0).toUpperCase() }}
                    </div>
                  }
                </div>
                <div class="absolute inset-0 bg-black/50 backdrop-blur-xs rounded-3xl opacity-0 group-hover:opacity-100 transition-opacity flex flex-col items-center justify-center text-white text-xs font-semibold gap-1">
                  <app-icon name="edit" [size]="18"></app-icon>
                  <span>Đổi ảnh</span>
                </div>
              </div>

              <!-- User Info -->
              <div class="flex-1 text-center sm:text-left">
                <div class="flex flex-wrap items-center justify-center sm:justify-start gap-3 mb-2">
                  <h1 class="text-2xl sm:text-3xl font-black text-[var(--text-primary)]">{{ user.username }}</h1>
                  <span
                    [class.bg-red-500]="user.role === 'ADMIN'"
                    [class.bg-purple-500]="user.role === 'MODERATOR'"
                    [class.bg-blue-600]="user.role === 'USER'"
                    class="text-[11px] font-bold text-white uppercase px-2.5 py-0.5 rounded-full shadow-xs"
                  >
                    {{ user.role }}
                  </span>
                </div>
                <p class="text-sm text-[var(--text-muted)] mb-4">{{ user.email }}</p>

                <!-- Level & Progress Bar -->
                <div class="bg-[var(--bg-secondary)] border border-[var(--border)] rounded-2xl p-4 max-w-md">
                  <div class="flex items-center justify-between text-xs font-semibold mb-2">
                    <span class="text-[var(--accent)] flex items-center gap-1.5">
                      <app-icon name="star" [size]="14"></app-icon>
                      Cấp độ {{ user.level || 1 }}
                    </span>
                    <span class="text-[var(--text-muted)]">{{ user.exp || 0 }} / {{ getNextLevelExp(user.level || 1) }} EXP</span>
                  </div>
                  <div class="w-full h-2.5 bg-[var(--border)] rounded-full overflow-hidden">
                    <div
                      class="h-full bg-linear-to-r from-[var(--accent)] to-pink-500 rounded-full transition-all duration-500"
                      [style.width.%]="getExpPercent(user.exp || 0, user.level || 1)"
                    ></div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Stats Grid -->
          <div class="grid grid-cols-2 sm:grid-cols-3 gap-4">
            <div class="bg-[var(--bg-card)] border border-[var(--border)] rounded-2xl p-5 flex items-center gap-4">
              <div class="w-12 h-12 rounded-xl bg-orange-500/10 text-orange-500 flex items-center justify-center">
                <app-icon name="flame" [size]="24"></app-icon>
              </div>
              <div>
                <p class="text-2xl font-black text-[var(--text-primary)]">{{ user.dailyStreak || 1 }}</p>
                <p class="text-xs text-[var(--text-muted)]">Ngày điểm danh liên tiếp</p>
              </div>
            </div>

            <div class="bg-[var(--bg-card)] border border-[var(--border)] rounded-2xl p-5 flex items-center gap-4">
              <div class="w-12 h-12 rounded-xl bg-blue-500/10 text-blue-500 flex items-center justify-center">
                <app-icon name="bookmark" [size]="24"></app-icon>
              </div>
              <div>
                <a routerLink="/followed" class="text-2xl font-black text-[var(--text-primary)] hover:text-[var(--accent)] transition-colors">Xem</a>
                <p class="text-xs text-[var(--text-muted)]">Truyện đang theo dõi</p>
              </div>
            </div>

            <div class="col-span-2 sm:col-span-1 bg-[var(--bg-card)] border border-[var(--border)] rounded-2xl p-5 flex items-center gap-4">
              <div class="w-12 h-12 rounded-xl bg-green-500/10 text-green-500 flex items-center justify-center">
                <app-icon name="history" [size]="24"></app-icon>
              </div>
              <div>
                <a routerLink="/history" class="text-2xl font-black text-[var(--text-primary)] hover:text-[var(--accent)] transition-colors">Xem</a>
                <p class="text-xs text-[var(--text-muted)]">Lịch sử đọc truyện</p>
              </div>
            </div>
          </div>
        </div>

        <!-- Edit Avatar Modal -->
        <app-modal [isOpen]="isAvatarModalOpen" title="Đổi ảnh đại diện" (closed)="closeAvatarModal()">
          <div class="space-y-4">
            <div>
              <label class="block text-xs font-semibold text-[var(--text-muted)] uppercase mb-2">Đường dẫn hình ảnh (URL)</label>
              <input
                type="text"
                [(ngModel)]="newAvatarUrl"
                placeholder="https://example.com/avatar.png"
                class="w-full bg-[var(--bg-secondary)] border border-[var(--border)] focus:border-[var(--accent)] text-[var(--text-primary)] rounded-xl px-4 py-2.5 text-sm outline-none"
              />
            </div>

            <!-- Avatar Preview -->
            @if (newAvatarUrl) {
              <div class="text-center py-2">
                <p class="text-xs text-[var(--text-muted)] mb-2">Xem trước:</p>
                <img [src]="newAvatarUrl" alt="Preview" class="w-24 h-24 rounded-2xl object-cover mx-auto border-2 border-[var(--accent)]" />
              </div>
            }

            <div class="flex justify-end gap-3 pt-4 border-t border-[var(--border)]">
              <button
                (click)="closeAvatarModal()"
                class="px-4 py-2 text-sm text-[var(--text-secondary)] hover:bg-[var(--bg-secondary)] rounded-xl transition-colors"
              >
                Hủy
              </button>
              <button
                (click)="saveAvatar()"
                [disabled]="isSavingAvatar"
                class="px-5 py-2 text-sm bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-white font-medium rounded-xl transition-colors disabled:opacity-50"
              >
                {{ isSavingAvatar ? 'Đang lưu...' : 'Cập nhật' }}
              </button>
            </div>
          </div>
        </app-modal>
      }
    </div>
  `
})
export class ProfilePageComponent {
  auth = inject(AuthService);
  private userService = inject(UserService);
  private toast = inject(ToastService);

  isAvatarModalOpen = false;
  newAvatarUrl = '';
  isSavingAvatar = false;

  getNextLevelExp(level: number): number {
    return level * 100;
  }

  getExpPercent(exp: number, level: number): number {
    const needed = this.getNextLevelExp(level);
    return Math.min(100, Math.round((exp / needed) * 100));
  }

  openAvatarModal() {
    this.newAvatarUrl = this.auth.currentUser()?.avatar || '';
    this.isAvatarModalOpen = true;
  }

  closeAvatarModal() {
    this.isAvatarModalOpen = false;
  }

  saveAvatar() {
    if (!this.newAvatarUrl) return;
    this.isSavingAvatar = true;
    this.userService.updateProfile({ avatar: this.newAvatarUrl }).subscribe({
      next: updated => {
        if (this.auth.currentUser()) {
          this.auth.updateCurrentUser({
            ...this.auth.currentUser()!,
            avatar: this.newAvatarUrl
          });
        }
        this.toast.success('Cập nhật ảnh đại diện thành công!');
        this.isSavingAvatar = false;
        this.closeAvatarModal();
      },
      error: () => {
        this.toast.error('Không thể cập nhật ảnh đại diện');
        this.isSavingAvatar = false;
      }
    });
  }
}
