// frontend/src/app/pages/categories/categories.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ComicService } from '../../core/services/app-services';
import { Genre } from '../../core/models';
import { IconComponent } from '../../shared/components/icon.component';
import { SkeletonComponent } from '../../shared/components/ui-components';

@Component({
  selector: 'app-categories-page',
  standalone: true,
  imports: [CommonModule, RouterLink, IconComponent, SkeletonComponent],
  template: `
    <div class="container mx-auto px-4 py-8">
      <!-- Breadcrumb / Header -->
      <div class="mb-8">
        <div class="flex items-center gap-2 text-sm text-[var(--text-muted)] mb-2">
          <a routerLink="/" class="hover:text-[var(--accent)] transition-colors">Trang chủ</a>
          <span>/</span>
          <span class="text-[var(--text-primary)]">Thể loại</span>
        </div>
        <h1 class="text-3xl font-black text-[var(--text-primary)] tracking-tight flex items-center gap-3">
          <app-icon name="grid" [size]="28" class="text-[var(--accent)]"></app-icon>
          Tất cả thể loại truyện
        </h1>
        <p class="text-[var(--text-muted)] mt-1">Khám phá hàng ngàn bộ truyện tranh phong phú được phân loại theo thể loại</p>
      </div>

      <!-- Categories Grid -->
      @if (loading()) {
        <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
          @for (i of [1,2,3,4,5,6,7,8,9,10,11,12]; track i) {
            <app-skeleton class="h-24 rounded-xl"></app-skeleton>
          }
        </div>
      } @else if (genres().length === 0) {
        <div class="text-center py-16 bg-[var(--bg-card)] rounded-2xl border border-[var(--border)]">
          <app-icon name="info" [size]="48" class="mx-auto text-[var(--text-muted)] mb-3"></app-icon>
          <p class="text-lg text-[var(--text-muted)]">Chưa có thể loại nào được tạo.</p>
        </div>
      } @else {
        <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
          @for (genre of genres(); track genre.id) {
            <a
              [routerLink]="['/comics']"
              [queryParams]="{ genre: genre.slug }"
              class="group relative overflow-hidden bg-[var(--bg-card)] hover:bg-[var(--bg-card-hover)] border border-[var(--border)] hover:border-[var(--accent)]/50 rounded-xl p-4 transition-all duration-300 hover:shadow-lg hover:-translate-y-1"
            >
              <div class="absolute -right-2 -bottom-2 opacity-5 group-hover:opacity-15 transition-opacity text-[var(--accent)]">
                <app-icon name="book-open" [size]="64"></app-icon>
              </div>

              <div class="relative z-10 flex flex-col justify-between h-full">
                <h3 class="font-bold text-base text-[var(--text-primary)] group-hover:text-[var(--accent)] transition-colors">
                  {{ genre.name }}
                </h3>
                @if (genre.description) {
                  <p class="text-xs text-[var(--text-muted)] line-clamp-2 mt-1">{{ genre.description }}</p>
                }
                <div class="flex items-center justify-between mt-3 pt-2 border-t border-[var(--border)]/50 text-xs text-[var(--text-muted)]">
                  <span>{{ genre.comicCount ?? 0 }} bộ truyện</span>
                  <app-icon name="chevron-right" [size]="14" class="group-hover:translate-x-1 transition-transform text-[var(--accent)]"></app-icon>
                </div>
              </div>
            </a>
          }
        </div>
      }
    </div>
  `
})
export class CategoriesPageComponent implements OnInit {
  private comicService = inject(ComicService);

  genres = signal<Genre[]>([]);
  loading = signal<boolean>(true);

  ngOnInit() {
    this.comicService.listCategories().subscribe({
      next: data => {
        this.genres.set(data || []);
        this.loading.set(false);
      },
      error: () => {
        this.loading.set(false);
      }
    });
  }
}

// src/app/(main)/categories/page.tsx
import React from "react";
import { Layers, BookOpen, ArrowRight } from "lucide-react";
import { comicService } from "@/services/comic.service";
import { PrefetchLink } from "@/components/common/PrefetchLink";

export const metadata = {
  title: "Danh Mục Thể Loại Truyện Tranh — TruyenKomi",
  description: "Tổng hợp tất cả các thể loại truyện tranh phong phú nhất: Hành động, Phiêu lưu, Chuyển sinh, Ngôn tình, Trinh thám...",
};

export default async function CategoriesPage() {
  const categories = await comicService.listCategories().catch(() => []);

  return (
    <div className="space-y-8">
      {/* Header Banner */}
      <div className="rounded-3xl border border-zinc-800 bg-gradient-to-r from-orange-500/10 via-zinc-900 to-zinc-900 p-6 sm:p-8">
        <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-orange-400 mb-1">
          <Layers className="h-4 w-4" /> Danh mục tổng hợp
        </div>
        <h1 className="text-2xl sm:text-3xl font-black text-zinc-100 tracking-tight">Tất Cả Thể Loại</h1>
        <p className="mt-1 text-xs sm:text-sm text-zinc-400">
          Khám phá và chọn lọc truyện tranh theo sở thích cá nhân từ hơn {categories.length} thể loại đặc sắc.
        </p>
      </div>

      {/* Category Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {categories.map((cat) => (
          <PrefetchLink
            key={cat.id}
            href={`/comics?genres=${cat.slug}`}
            className="group flex flex-col justify-between rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5 transition duration-300 hover:-translate-y-1 hover:border-orange-500/40 hover:bg-zinc-800/60 hover:shadow-xl hover:shadow-orange-500/5 active:scale-[0.98]"
          >
            <div>
              <div className="flex items-center justify-between">
                <h3 className="text-base font-bold text-zinc-100 group-hover:text-orange-400 transition">
                  {cat.name}
                </h3>
                <span className="flex items-center gap-1 rounded-md bg-orange-500/10 px-2 py-0.5 text-[11px] font-bold text-orange-400">
                  <BookOpen className="h-3 w-3" /> {cat.comicCount || 0}
                </span>
              </div>
              <p className="mt-2 text-xs text-zinc-400 line-clamp-2 leading-relaxed">
                {cat.description || `Tổng hợp các bộ truyện tranh thể loại ${cat.name} hay nhất.`}
              </p>
            </div>

            <div className="mt-4 flex items-center gap-1 text-xs font-semibold text-orange-400 group-hover:text-orange-300 transition">
              <span>Khám phá ngay</span>
              <ArrowRight className="h-3 w-3 transition-transform group-hover:translate-x-1" />
            </div>
          </PrefetchLink>
        ))}
      </div>
    </div>
  );
}
